// services/leads.api.ts
import axios, { type AxiosRequestConfig } from "axios";

// ====================== Types ======================
export type Department = {
  id: number;
  name: string;
  is_active: boolean;
};

export type Clinic = {
  id: number;
  name: string;
  department: Department[];
};

export type Employee = {
  id: number;
  emp_name: string;
  emp_type: string;
  department_name: string;
  email?: string;
  emp_email?: string;
  user_email?: string;
  official_email?: string;
};

export type Interest = {
  id: string;
  name: string;
  is_active: boolean;
  clinic: number;
};

export type LeadDocument = {
  id: string;
  file: string;
  uploaded_at: string;
};

export type Lead = {
  status: string | undefined;
  id: string;
  stage_id?: string | number;
  clinic_id: number;
  clinic_name: string;
  department_id: number;
  department_name: string;
  full_name: string;
  contact_no: string;
  email?: string;
  age?: number;
  gender?: "male" | "female";
  marital_status?: "single" | "married";
  location?: string;
  address?: string;
  partner_inquiry: boolean;
  partner_full_name?: string;
  partner_age?: number;
  partner_gender?: "male" | "female";
  source: string;
  sub_source?: string;
  lead_status?:
    | "New"
    | "Contacted"
    | "Follow-Ups"
    | "Converted"
    | "Lost"
    | "Cycle Conversion"
    | "Appointment";
  next_action_type?: string;
  next_action_status?: string;
  next_action_description?: string;
  action_status?: "to_do" | "in_progress" | "completed" | null;
  assigned_to_id?: number;
  assigned_to_name?: string;
  created_by_id?: number;
  created_by_name?: string;
  treatment_interest?: string | string[] | { id: string; name: string }[];
  book_appointment: boolean;
  appointment_date: string;
  slot: string;
  remark?: string;
  documents?: LeadDocument[];
  is_active: boolean;
  created_at: string;
  modified_at: string;
  referral_department_id?: number | null;
  referral_department_name?: string | null;
  referral_source_id?: number | null;

  // ── Lead Generated By (set in Add New Lead → "Lead Generated By" field) ───
  personal_id?: number | null;
  personal_name?: string | null;
  lead_generated_by_id?: number | null;
  lead_generated_by_name?: string | null;

  // ── Contact Information (contracts app) ───────────────────────────────────
  contact_full_name?: string | null;
  contact_designation?: string | null;
  contact_phone?: string | null;
  contact_email?: string | null;
};

export type LeadPayload = {
  clinic_id: number;
  department_id: number;
  stage_id?: string | number | null;
  campaign_id?: string | null;
  assigned_to_id?: number | null;
  assigned_to_name?: string | null;
  personal_id?: number | null;
  personal_name?: string | null;
  full_name: string;
  contact_no: string;
  age?: number | null;
  gender?: "male" | "female" | null;
  marital_status?: "single" | "married" | null;
  email?: string | null;
  language_preference?: string;
  location?: string;
  address?: string;
  partner_inquiry: boolean;
  partner_full_name?: string;
  partner_age?: number | null;
  partner_gender?: "male" | "female" | null;
  source: string;
  sub_source?: string;
  lead_status?:
    | "new"
    | "contacted"
    | "appointment"
    | "follow up"
    | "negotiation"
    | "proposal sent"
    | "contract signed"
    | "converted"
    | "cycle_conversion"
    | "lost"
    | "lost lead";
  next_action_status?: string | null;
  next_action_description?: string;
  next_action_type?: string;
  action_status?: "to_do" | "in_progress" | "completed" | null;
  treatment_interest?: string | string[] | { id: string; name: string }[];
  book_appointment: boolean;
  appointment_date: string | null;
  slot: string;
  remark?: string;
  is_active: boolean;
  referral_department_id?: number | null;

  // ── Contact Information (contracts app) ───────────────────────────────────
  contact_full_name?: string | null;
  contact_designation?: string | null;
  contact_phone?: string | null;
  contact_email?: string | null;
};

// Referral source object — sent alongside payload for contracts app
export type ReferralSourceObject = {
  first_name: string;
  last_name: string;
  email: string;
  role: string;
};

// ====================== Lead Email Types ======================
export type LeadEmailPayload = {
  lead: string;
  subject: string;
  email_body: string;
  sender_email?: string | null;
  scheduled_at?: string | null;
  send_now?: boolean;
  cc?: string[];
  bcc?: string[];
  additional_to?: string[];
};

export type LeadEmailStatus =
  | "DRAFT"
  | "SCHEDULED"
  | "SENT"
  | "FAILED"
  | "CANCELLED";

export type LeadEmailResponse = {
  id: number;
  lead: string;
  subject: string;
  email_body: string;
  sender_email?: string | null;
  scheduled_at?: string | null;
  status: LeadEmailStatus;
  sent_at?: string | null;
  failed_reason?: string | null;
  created_at: string;
  send_now?: boolean;
};

export type LeadMailListItem = {
  id: number | string;
  lead_uuid?: string;
  subject: string;
  sender_email?: string | null;
  email_body: string;
  status: LeadEmailStatus | string;
  failed_reason?: string | null;
  scheduled_at?: string | null;
  sent_at?: string | null;
  created_at: string;
};

// ====================== Twilio Types ======================
export type TwilioSMS = {
  id: string | number;
  sid: string;
  to_number: string;
  from_number: string;
  body: string;
  status: string;
  direction: string;
  created_at: string;
};

export type TwilioCall = {
  id: string | number;
  sid: string;
  to_number: string;
  from_number: string;
  status: string;
  direction: string;
  duration?: string | number;
  created_at: string;
};

// ====================== Token Helpers ======================
const TOKEN_KEYS = ["auth_token", "access_token", "access", "token"] as const;
const REFRESH_KEYS = ["refresh_token", "refresh"] as const;

export const getAccessToken = (): string | null => {
  for (const key of TOKEN_KEYS) {
    const val = localStorage.getItem(key);
    if (val) return val;
  }
  return null;
};

export const getRefreshToken = (): string | null => {
  for (const key of REFRESH_KEYS) {
    const val = localStorage.getItem(key);
    if (val) return val;
  }
  return null;
};

export const setTokens = (access: string, refresh?: string): void => {
  localStorage.setItem("auth_token", access);
  localStorage.setItem("access_token", access);
  if (refresh) {
    localStorage.setItem("refresh_token", refresh);
    localStorage.setItem("refresh", refresh);
  }
};

export const clearTokens = (): void => {
  [...TOKEN_KEYS, ...REFRESH_KEYS].forEach((k) => localStorage.removeItem(k));
};

// ====================== Axios Instance ======================
const resolveApiBaseUrl = (): string => {
  const configured = (
    (import.meta as unknown as { env: Record<string, string | undefined> }).env
      ?.VITE_API_BASE_URL
  )?.trim();

  if (configured) return configured;

  if (typeof window !== "undefined" && window.location?.origin) {
    return `${window.location.origin}/api`;
  }

  return "http://127.0.0.1:8000/api";
};

const API_BASE_URL: string = resolveApiBaseUrl();

const api = axios.create({
  baseURL: API_BASE_URL,
  // headers: { "Content-Type": "application/json" },
});

// ── Request interceptor ───────────────────────────────────────────────────────
api.interceptors.request.use(
  (config) => {
    const token = getAccessToken();
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    } else if (import.meta.env.DEV) {
      console.warn(
        `[api] ⚠️ No auth token found for ${config.method?.toUpperCase()} ${config.url}. ` +
          `Checked: ${TOKEN_KEYS.join(", ")}`,
      );
    }
    return config;
  },
  (error) => Promise.reject(error),
);
api.interceptors.request.use((config) => {
  if (config.data instanceof FormData) {
    if (config.headers && typeof config.headers.delete === "function") {
      config.headers.delete("Content-Type");
    } else if (config.headers) {
      delete config.headers["Content-Type"];
    }
  }
  return config;
});

// ── Response interceptor ──────────────────────────────────────────────────────
let isRefreshing = false;
let refreshQueue: Array<{
  resolve: (token: string) => void;
  reject: (err: unknown) => void;
}> = [];

const drainQueue = (err: unknown, token: string | null = null): void => {
  refreshQueue.forEach(({ resolve, reject }) =>
    err ? reject(err) : resolve(token!),
  );
  refreshQueue = [];
};

api.interceptors.response.use(
  (response) => response,
  async (error) => {
    const status: number | undefined = error?.response?.status;
    const url: string = error?.config?.url ?? "";
    const raw = error?.response?.data;
    const isCanceledRequest =
      error?.code === "ERR_CANCELED" || error?.name === "CanceledError";
    const skipLog = Boolean(
      (error?.config as { __skipErrorLog?: boolean } | undefined)
        ?.__skipErrorLog,
    );

    const normalizeError = (value: unknown): string => {
      if (value == null) return "Unknown error";
      if (typeof value === "string") return value;
      if (typeof value === "number" || typeof value === "boolean")
        return String(value);
      if (Array.isArray(value)) {
        const first = value[0];
        return first == null ? "Unknown error" : normalizeError(first);
      }
      if (typeof value === "object") {
        const obj = value as Record<string, unknown>;
        if (typeof obj.detail === "string") return obj.detail;
        if (typeof obj.message === "string") return obj.message;
        if (typeof obj.error === "string") return obj.error;
        const entries = Object.entries(obj);
        if (!entries.length) return "Unknown error";
        return entries
          .slice(0, 4)
          .map(([k, v]) => `${k}: ${normalizeError(v)}`)
          .join(" | ");
      }
      return "Unknown error";
    };

    if (!skipLog && !isCanceledRequest) {
      console.error(
        `❌ API Error [${status}] ${url}: ${normalizeError(raw ?? error?.message)}`,
      );
    }

    const originalRequest = error.config as AxiosRequestConfig & {
      _retry?: boolean;
    };

    const isAuthEndpoint =
      url.includes("/token/refresh/") || url.includes("/auth/login/");

    if (status === 401 && !originalRequest._retry && !isAuthEndpoint) {
      const refreshToken = getRefreshToken();

      if (!refreshToken) {
        if (import.meta.env.DEV) {
          console.warn(
            "[api] 401 with no refresh token — redirecting to /login.",
          );
        }
        clearTokens();
        window.location.href = "/login";
        return Promise.reject(error);
      }

      if (isRefreshing) {
        return new Promise<string>((resolve, reject) => {
          refreshQueue.push({ resolve, reject });
        }).then((newToken) => {
          originalRequest.headers = originalRequest.headers ?? {};
          originalRequest.headers["Authorization"] = `Bearer ${newToken}`;
          return api(originalRequest);
        });
      }

      originalRequest._retry = true;
      isRefreshing = true;

      try {
        const { data } = await axios.post(
          `${API_BASE_URL}/token/refresh/`,
          { refresh: refreshToken },
          { headers: { "Content-Type": "application/json" } },
        );

        const newAccess: string = data.access;
        setTokens(newAccess, data.refresh ?? undefined);
        drainQueue(null, newAccess);

        originalRequest.headers = originalRequest.headers ?? {};
        originalRequest.headers["Authorization"] = `Bearer ${newAccess}`;
        return api(originalRequest);
      } catch (refreshErr) {
        drainQueue(refreshErr, null);
        clearTokens();
        window.location.href = "/login";
        return Promise.reject(refreshErr);
      } finally {
        isRefreshing = false;
      }
    }

    return Promise.reject(error);
  },
);

// ====================== FormData Helper ======================
/**
 * Safely appends a LeadPayload field to FormData.
 *
 * Rules:
 *  - documents         → always skipped (files are appended separately as File objects)
 *  - undefined / null  → skipped entirely (field not sent)
 *  - boolean           → "true" / "false"
 *  - treatment_interest (Array) → each item appended as a separate string value
 *                        so Django REST Framework receives repeated fields and
 *                        deserialises them as a proper list (avoids the
 *                        "Not a valid string." error that occurs when the whole
 *                        array is JSON-stringified into a single form value)
 *  - other Arrays      → JSON-stringified
 *  - everything else   → String(value)
 */
const appendPayloadToFormData = (
  formData: FormData,
  data: LeadPayload | Partial<LeadPayload>,
): void => {
  (Object.keys(data) as (keyof typeof data)[]).forEach((key) => {
    if ((key as string) === "documents") return;

    const value = data[key];

    if (value === undefined || value === null) return;

    if (typeof value === "boolean") {
      formData.append(key, value ? "true" : "false");
      return;
    }

    if (Array.isArray(value)) {
      // ── treatment_interest: append each item individually so DRF reads them
      // as a proper string list rather than a single JSON-encoded string.
      if (key === "treatment_interest") {
        (value as unknown[]).forEach((item) => {
          const str =
            item == null
              ? ""
              : typeof item === "string"
                ? item
                : typeof item === "object" && "id" in (item as object)
                  ? String((item as { id: string }).id)
                  : String(item);
          if (str) formData.append(key, str);
        });
      } else {
        formData.append(key, JSON.stringify(value));
      }
      return;
    }

    formData.append(key, String(value));
  });
};

// ====================== Lead API ======================
const storedClinicId = (): number =>
  Number(localStorage.getItem("clinic_id") ?? 0);

const removeBlankUpdateFields = <T extends Record<string, unknown>>(
  payload: T,
): Partial<T> => {
  const next = { ...payload } as Record<string, unknown>;

  // ── Remove blank contact_no ──
  if (
    next.contact_no === null ||
    next.contact_no === undefined ||
    (typeof next.contact_no === "string" && next.contact_no.trim() === "")
  ) {
    delete next.contact_no;
  }

  // ── Keep action_status (task status) even if empty/null for update ──
  // This ensures it gets properly processed by the backend
  // (removing it would prevent updates to clear the field)

  return next as Partial<T>;
};

const normalizeTreatmentInterest = (
  value: LeadPayload["treatment_interest"],
): string | string[] | undefined => {
  if (value == null) return undefined;
  if (typeof value === "string") {
    const trimmed = value.trim();
    return trimmed ? trimmed : undefined;
  }

  const normalized = (value as unknown[])
    .map((item) => {
      if (item == null) return "";
      if (typeof item === "string") return item.trim();
      if (typeof item === "object" && "id" in (item as object)) {
        return String((item as { id: string }).id).trim();
      }
      return String(item).trim();
    })
    .filter(Boolean);

  return normalized.length ? normalized : undefined;
};

const sanitizeLeadCreatePayload = (data: LeadPayload): LeadPayload => {
  const requiredKeys: (keyof LeadPayload)[] = [
    "clinic_id",
    "department_id",
    "full_name",
    "contact_no",
    "source",
    "partner_inquiry",
    "book_appointment",
    "is_active",
    "slot",
  ];

  const next = { ...data } as Record<string, unknown>;

  next.treatment_interest = normalizeTreatmentInterest(data.treatment_interest);

  if (!data.book_appointment) {
    delete next.appointment_date;
    if (typeof next.slot === "string" && next.slot.trim() === "") {
      delete next.slot;
    }
  }

  (Object.keys(next) as (keyof LeadPayload)[]).forEach((key) => {
    if (requiredKeys.includes(key)) return;

    const value = next[key as string];

    if (value === undefined || value === null) {
      delete next[key as string];
      return;
    }

    if (typeof value === "string" && value.trim() === "") {
      delete next[key as string];
    }
  });

  return next as LeadPayload;
};

const buildMinimalLeadCreatePayload = (data: LeadPayload): LeadPayload => ({
  clinic_id: data.clinic_id,
  department_id: data.department_id,
  full_name: data.full_name,
  contact_no: data.contact_no,
  source: data.source,
  partner_inquiry: data.partner_inquiry,
  book_appointment: false,
  appointment_date: null,
  slot: "",
  is_active: data.is_active,
});

const isServer500 = (error: unknown): boolean =>
  axios.isAxiosError(error) && error.response?.status === 500;

const getLeadId = (lead: Lead): string => String(lead.id);

let leadsListController: AbortController | null = null;

export const LeadAPI = {
  list: async (clinicId: number) => {
    leadsListController?.abort();

    // Create new controller
    leadsListController = new AbortController();

    try {
      const res = await api.get(`/leads/list/?clinic_id=${clinicId}`, {
        signal: leadsListController.signal,
      });

      return res.data;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } catch (error: any) {
      if (error?.code === "ERR_CANCELED" || error?.name === "CanceledError") {
        console.log("Previous leads request cancelled");
        return [];
      }

      throw error;
    }
  },

  create: async (
    data: LeadPayload,
    referralSource?: ReferralSourceObject,
  ): Promise<Lead> => {
    const sanitized = sanitizeLeadCreatePayload(data);
    const body = referralSource
      ? { ...sanitized, referral_source: referralSource }
      : sanitized;
    try {
      const response = await api.post<Lead>(
        `/leads/?clinic_id=${data.clinic_id}`,
        body,
        {
          headers: {
            "X-Clinic-Id": String(data.clinic_id),
          },
        },
      );
      console.log("✅ Lead created:", response.data);
      return response.data;
    } catch (error) {
      if (!isServer500(error)) {
        throw error;
      }

      const minimal = buildMinimalLeadCreatePayload(sanitized);
      const minimalBody = referralSource
        ? { ...minimal, referral_source: referralSource }
        : minimal;

      console.warn(
        "[LeadAPI.create] Full payload create failed with 500. Retrying with minimal payload.",
      );

      const retryResponse = await api.post<Lead>(
        `/leads/?clinic_id=${data.clinic_id}`,
        minimalBody,
        {
          headers: {
            "X-Clinic-Id": String(data.clinic_id),
          },
        },
      );

      const createdLead = retryResponse.data;

      try {
        const enrichedLead = await LeadAPI.update(getLeadId(createdLead), {
          ...sanitized,
          clinic_id: createdLead.clinic_id ?? sanitized.clinic_id,
          department_id: createdLead.department_id ?? sanitized.department_id,
        });
        return enrichedLead;
      } catch (enrichError) {
        console.warn(
          "[LeadAPI.create] Minimal create succeeded, but enrich update failed.",
          enrichError,
        );
        return createdLead;
      }
    }
  },

  createWithDocuments: async (
    data: LeadPayload,
    files: File[],
    referralSource?: ReferralSourceObject,
  ): Promise<Lead> => {
    const createdLead = await LeadAPI.create(data, referralSource);

    if (!files.length) {
      return createdLead;
    }

    try {
      const updatedLead = await LeadAPI.uploadDocuments(
        getLeadId(createdLead),
        files,
      );
      console.log("✅ Lead created and documents uploaded:", updatedLead);
      return updatedLead;
    } catch (uploadError) {
      console.warn(
        "[LeadAPI.createWithDocuments] Lead was created, but document upload failed.",
        uploadError,
      );
      return createdLead;
    }
  },

  getById: async (leadId: string): Promise<Lead> => {
    const response = await api.get<Lead>(
      `/leads/${leadId}/?clinic_id=${storedClinicId()}`,
    );
    return response.data;
  },

  update: async (leadId: string, data: Partial<LeadPayload>): Promise<Lead> => {
    const clinicId = data.clinic_id ?? storedClinicId();
    const sanitizedData = removeBlankUpdateFields(data);
    const response = await api.put<Lead>(
      `/leads/${leadId}/update/?clinic_id=${clinicId}`,
      sanitizedData,
      {
        headers: {
          "X-Clinic-Id": String(clinicId),
        },
      },
    );
    return response.data;
  },

  updateWithDocuments: async (
    leadId: string,
    data: Partial<LeadPayload>,
    files: File[],
  ): Promise<Lead> => {
    const formData = new FormData();
    const sanitizedData = removeBlankUpdateFields(data);

    appendPayloadToFormData(formData, sanitizedData as Partial<LeadPayload>);

    files.forEach((file) => formData.append("documents", file));

    const clinicId = data.clinic_id ?? storedClinicId();
    const response = await api.put<Lead>(
      `/leads/${leadId}/update/?clinic_id=${clinicId}`,
      formData,
      {
        headers: {
          "X-Clinic-Id": String(clinicId),
        },
      },
    );
    console.log("✅ Lead + documents updated:", response.data);
    return response.data;
  },

  activate: async (leadId: string): Promise<void> => {
    await api.post(`/leads/${leadId}/activate/?clinic_id=${storedClinicId()}`);
  },

  inactivate: async (leadId: string): Promise<void> => {
    await api.patch(
      `/leads/${leadId}/inactivate/?clinic_id=${storedClinicId()}`,
    );
  },

  delete: async (leadId: string): Promise<void> => {
    await api.patch(`/leads/${leadId}/delete/?clinic_id=${storedClinicId()}`);
  },

  getDocuments: async (leadId: string): Promise<LeadDocument[]> => {
    const lead = await LeadAPI.getById(leadId);
    return lead.documents ?? [];
  },

  uploadDocument: async (leadId: string, file: File): Promise<Lead> => {
    const formData = new FormData();
    formData.append("documents", file);
    const response = await api.put<Lead>(
      `/leads/${leadId}/update/?clinic_id=${storedClinicId()}`,
      formData,
      {
        headers: {
          "X-Clinic-Id": String(storedClinicId()),
        },
      },
    );
    return response.data;
  },

  uploadDocuments: async (leadId: string, files: File[]): Promise<Lead> => {
    const current = await LeadAPI.getById(leadId);
    const formData = new FormData();
    const safeFields: Record<string, string> = {
      clinic_id: String(current.clinic_id ?? 1),
      department_id: String(current.department_id ?? 1),
      full_name: current.full_name ?? "",
      contact_no: current.contact_no ?? "",
      source: current.source ?? "",
      book_appointment: current.book_appointment ? "true" : "false",
      appointment_date: current.appointment_date ?? "",
      slot: current.slot ?? "",
      partner_inquiry: current.partner_inquiry ? "true" : "false",
      is_active: current.is_active ? "true" : "false",
    };
    Object.entries(safeFields).forEach(([k, v]) => formData.append(k, v));
    const normalizedTreatmentInterest = Array.isArray(
      current.treatment_interest,
    )
      ? current.treatment_interest
      : current.treatment_interest
        ? [current.treatment_interest]
        : [];

    normalizedTreatmentInterest.forEach((item) => {
      const value = typeof item === "object" ? item.id : String(item);

      if (value) {
        formData.append("treatment_interest", value);
      }
    });
    files.forEach((file) => formData.append("documents", file));
    const clinicId = current.clinic_id ?? storedClinicId();
    const response = await api.put<Lead>(
      `/leads/${leadId}/update/?clinic_id=${clinicId}`,
      formData,
      {
        headers: {
          "X-Clinic-Id": String(clinicId),
        },
      },
    );
    return response.data;
  },
};

// ====================== Lead Email API ======================
export const LeadEmailAPI = {
  create: async (
    data: LeadEmailPayload,
    options?: { suppressErrorLog?: boolean },
  ): Promise<LeadEmailResponse> => {
    const requestConfig: AxiosRequestConfig = {};
    (
      requestConfig as AxiosRequestConfig & { __skipErrorLog?: boolean }
    ).__skipErrorLog = options?.suppressErrorLog === true;
    const response = await api.post<LeadEmailResponse>(
      "/lead-email/",
      data,
      requestConfig,
    );
    console.log("✅ Lead email created:", response.data);
    return response.data as LeadEmailResponse;
  },

  sendNow: async (
    data: Omit<LeadEmailPayload, "send_now">,
  ): Promise<LeadEmailResponse> =>
    LeadEmailAPI.create({ ...data, send_now: true }),

  saveAsDraft: async (
    data: Omit<LeadEmailPayload, "send_now">,
  ): Promise<LeadEmailResponse> =>
    LeadEmailAPI.create({ ...data, send_now: false }),

  list: async (leadUuid?: string): Promise<LeadMailListItem[]> => {
    const params = leadUuid ? { lead_uuid: leadUuid } : {};
    const response = await api.get<LeadMailListItem[]>("/lead-mail/", {
      params,
    });
    return response.data;
  },

  listByLead: async (leadId: string): Promise<LeadMailListItem[]> =>
    LeadEmailAPI.list(leadId),
};

// ====================== Email Template Types ======================
export type EmailTemplate = {
  id: string | number;
  name: string;
  subject: string;
  body: string;
  description?: string;
  use_case?: string;
  is_active?: boolean;
  created_at?: string;
};

export type EmailTemplatePayload = {
  clinic: number;
  name: string;
  subject: string;
  body: string;
  description?: string;
  use_case?: string;
  created_by: number;
  is_active?: boolean;
};

// ====================== Email Template API ======================
export const EmailTemplateAPI = {
  list: async (): Promise<EmailTemplate[]> => {
    const response = await api.get<EmailTemplate[]>("/templates/mail/");
    const data = response.data;
    if (Array.isArray(data)) return data;
    if (data && typeof data === "object" && "results" in (data as object)) {
      return (data as { results: EmailTemplate[] }).results ?? [];
    }
    return [];
  },

  create: async (payload: EmailTemplatePayload): Promise<EmailTemplate> => {
    const response = await api.post<EmailTemplate>(
      "/templates/mail/create/",
      payload,
    );
    console.log("✅ Email template created:", response.data);
    return response.data;
  },

  getById: async (templateId: string | number): Promise<EmailTemplate> => {
    const response = await api.get<EmailTemplate>(
      `/templates/mail/${templateId}/`,
    );
    return response.data;
  },

  delete: async (templateId: string | number): Promise<void> => {
    await api.delete(`/templates/mail/${templateId}/delete/`);
  },
};

// ====================== Twilio API ======================
export const TwilioAPI = {
  makeCall: async (payload: {
    lead_uuid: string;
    to: string;
  }): Promise<unknown> => {
    const clinicId = storedClinicId();
    const response = await api.post("/twilio/make-call/", payload, {
      params: clinicId > 0 ? { clinic_id: clinicId } : undefined,
      headers:
        clinicId > 0
          ? {
              "X-Clinic-Id": String(clinicId),
            }
          : undefined,
    });
    console.log("📞 Call initiated:", response.data);
    return response.data;
  },

  sendSMS: async (payload: {
    lead_uuid: string;
    to: string;
    message: string;
  }): Promise<unknown> => {
    const clinicId = storedClinicId();
    const response = await api.post("/twilio/send-sms/", payload, {
      params: clinicId > 0 ? { clinic_id: clinicId } : undefined,
      headers:
        clinicId > 0
          ? {
              "X-Clinic-Id": String(clinicId),
            }
          : undefined,
    });
    console.log("💬 SMS sent:", response.data);
    return response.data;
  },

  getSMSHistory: async (leadUuid: string): Promise<TwilioSMS[]> => {
    const response = await api.get<TwilioSMS[]>(
      `/twilio/sms-history/?lead_uuid=${leadUuid}`,
    );
    return response.data;
  },

  getCallHistory: async (leadUuid: string): Promise<TwilioCall[]> => {
    const response = await api.get<TwilioCall[]>(
      `/twilio/call-history/?lead_uuid=${leadUuid}`,
    );
    return response.data;
  },
};

// ====================== Clinic API ======================
export const ClinicAPI = {
  getById: async (clinicId: number): Promise<Clinic> => {
    try {
      const response = await api.get<Clinic>(`/clinics/${clinicId}/detail/`);
      return response.data;
    } catch {
      const fallback = await api.get<Clinic>(`/get_clinic/${clinicId}/`);
      return fallback.data;
    }
  },

  create: async (data: {
    name: string;
    department: string[];
  }): Promise<Clinic> => {
    const response = await api.post<Clinic>("/clinics", data);
    return response.data;
  },

  update: async (
    clinicId: number,
    data: { name: string; department: string[] },
  ): Promise<Clinic> => {
    const response = await api.put<Clinic>(`/clinics/${clinicId}/`, data);
    return response.data;
  },

  getEmployees: async (clinicId: number): Promise<Employee[]> => {
    const response = await api.get<Employee[] | { results: Employee[] }>(
      `/clinics/${clinicId}/employees/`,
    );
    const data = response.data;
    if (!Array.isArray(data)) {
      if (
        data &&
        typeof data === "object" &&
        "results" in data &&
        Array.isArray(data.results)
      ) {
        return data.results;
      }
      return [];
    }
    return data;
  },
};

// ====================== Department API ======================
export const DepartmentAPI = {
  listByClinic: async (clinicId: number): Promise<Department[]> => {
    try {
      const response = await api.get<Department[]>(
        `/departments/?clinic_id=${clinicId}`,
      );
      const data = response.data;
      return Array.isArray(data) ? data : [];
    } catch {
      const clinic = await ClinicAPI.getById(clinicId);
      return clinic.department || [];
    }
  },

  listActiveByClinic: async (clinicId: number): Promise<Department[]> => {
    const departments = await DepartmentAPI.listByClinic(clinicId);
    return departments.filter((dept) => dept.is_active);
  },
};

// ====================== Interest API ======================
export const InterestAPI = {
  listActiveByClinic: async (clinicId: number) => {
    const res = await api.get("/interests/", {
      headers: {
        "X-Clinic-Id": clinicId,
      },
    });

    return res.data;
  },
};

// ====================== Employee API ======================
export const EmployeeAPI = {
  listByClinic: async (clinicId: number): Promise<Employee[]> =>
    ClinicAPI.getEmployees(clinicId),

  create: async (data: {
    user_id: number;
    clinic_id: number;
    department_id: number;
    emp_type: string;
    emp_name: string;
  }): Promise<Employee> => {
    const response = await api.post<Employee>("/employees/", data);
    return response.data;
  },
};

export { api };